### PR TITLE
Tn edit

### PR DESCRIPTION
**Pull request by CyannRogue**
Hi @iamleomoko Please review the added documents

### CODE REVIEW

**Comment by iamleomoko** [comment]
Hey @CyannRogue can you create a ticket for these changes.

**Comment by CyannRogue** [comment]
Ok

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by iamleomoko** [comment]
@CyannRogue are the more changes expected to come to this PR ?

**Comment by CyannRogue** [comment]
Yes

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by iamleomoko** [comment]
Make use of proper English drama, please. 

Have your pull request as a draft since you are still working on it (WIP), then when you are done with the task, you then convert it to a PR

I will change it for you so long

**Comment by iamleomoko** [comment]
It looks like I'm unable to change it to a draft, can you change it yourself then?

**Comment by CyannRogue** [comment]
Hello @iamleomoko, could you please look at this? If there are any issues or anything that needs to be added, we still have time to make the necessary adjustments.

**Review by iamleomoko — APPROVED** [review]

**Pull request merged**
